### ISSUE TITLE
Meet error when trying to enable video upload with tutor-minio

### ISSUE THREAD

**Issue by pcliupc** [overhangio/tutor-minio#1]
I am trying to enable video upload in studio by using tutor-minio. The situation is I can upload files to bucket by minio browser, but meets 400 error when upload videos from studio.

I tried curl the url generated by cms and got more error messages as below:

`<Error><Code>AccessDenied</Code><Message>There were headers present in the request which were not signed</Message><Key>c8c444f7-75f5-4b67-96cd-ef27b0d2ba63</Key><BucketName>openedxvideos</BucketName><Resource>/openedxvideos/c8c444f7-75f5-4b67-96cd-ef27b0d2ba63</Resource><RequestId>160ED65CD579CAB4</RequestId><HostId>7bb621e0-867a-4d4f-af73-e563e2a9d247</HostId></Error>`

By the way, I need to upgrade boto to 2.49.0, otherwise config parser error happens during generating upload url.

**Comment by pcliupc** [comment]
@regisb Have you met similar problems before?

**Comment by regisb** [comment]
Yes, this is an issue that I tried (and failed) to fix upstream. See this PR: https://github.com/edx/edx-platform/pull/22080
To clarify: this is not caused by the minio plugin, but by a limitation of edx-platform. I hope I will be able to fix this in the next Open edX release (Juniper).

**Comment by pcliupc** [comment]
@regisb Thanks, the info you provided is really helpful.

Another issue I met and solved is if other metadata fields are set by set_metadata(), they also need to be set to headers explicitly when generate_url.
Not sure whether this relates to my local configurations.

**Comment by regisb** [comment]
Video upload is closely linked to edX' video pipeline, which is *not* open source. According to my tests, the video upload page cannot work, even if we somehow make it compatible with minio.
