### ISSUE TITLE
Export Library and Course error with MINIO (S3) integrated

### ISSUE THREAD

**Issue by sbernesto** [overhangio/tutor-minio#13]
Tutor version: 13.1.0

Hi,

When i trying to export a course I get this error

![image](https://user-images.githubusercontent.com/15792476/150384475-03f6673f-193b-4ad6-93bf-d87c688cb7da.png)

`
minio_1                      | API: SYSTEM()
minio_1                      | Time: 17:02:51 UTC 01/18/2022
minio_1                      | DeploymentID: 10659882-5f67-4d3b-9bb8-2a77299296a5
minio_1                      | Error: invalid semicolon separator in query (*errors.errorString)
minio_1                      |        3: cmd/auth-handler.go:110:cmd.getRequestAuthType()
minio_1                      |        2: cmd/auth-handler.go:489:cmd.setAuthHandler.func1()
minio_1                      |        1: net/http/server.go:2046:http.HandlerFunc.Serv
`

**Comment by regisb** [comment]
See the corresponding conversation here: https://discuss.overhang.io/t/export-library-and-course-error-with-minio-s3-integrated/2338
