### ISSUE TITLE
ACTIVATE_MINIO variable in config.yml

### ISSUE THREAD

**Issue by ramshankar1988** [overhangio/tutor-minio#3]
Need to provide ACTIVATE_MINIO = true or false in config.yml to host the minio server in different cluster/min.io server by avoiding the pod creation in parent cluster [just like mongo, mysql configuration].

Ref: https://discuss.overhang.io/t/aws-s3-configuration-for-k8s/629/6

**Comment by regisb** [comment]
@ramshankar1988 Gateway support was recently introduced in this plugin: with this change, the MinIO server acts as a gateway to S3 or Azure, for instance: https://docs.minio.io/docs/minio-gateway-for-s3.html
Does that fill your requirement? I believe it should be possible to run MinIO separately, and then run a separate MinIO instance to point to the first one, as a S3 Gateway. Do you see what I mean?
