### ISSUE TITLE
tutor-minio codebase Python 3.12 upgrade

### ISSUE THREAD

**Issue by DawoudSheraz** [overhangio/tutor-minio#36]
- [x] Ensure tutor-minio codebase is compatible with Python 3.12
- ~~Update Python to 3.12 in Dockerfile for nightly and ensure the image builds as expected. The changes would be merged to nightly~~ N/A  

See https://github.com/overhangio/tutor/issues/1004 for the context.

**Comment by FahadKhalid210** [comment]
This plugin doesn't have any Dockerfile.
