### ISSUE TITLE
Graded download issues

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/tutor-minio#43]
This is a duplicate of https://github.com/hastexo/tutor-contrib-s3/issues/77

Hi. I noticed a couple of issues related to GRADES_DOWNLOAD.
There's a section in the instructor tab of each course, where instructors can download grades in a CSV format.
Inside `lms/djangoapps/instructor_task/models.py`, where we create a `DjangoStorageReportStore`, it needs these values from the config, otherwise will fail:

- STORAGE_TYPE
- BUCKET
- ROOT_PATH
- CUSTOM_DOMAIN (if exists)

https://github.com/openedx/edx-platform/blob/f3f160f4f20f7bbde45fe0d48ac9626a694afb93/lms/djangoapps/instructor_task/models.py#L230-L242

Oddly, it's not reading them from `AWS_S3_` configs.

In the plugin, just a bucket_name and a location kwargs are overridden.

```python
GRADES_DOWNLOAD["STORAGE_KWARGS"] = {"location": GRADES_DOWNLOAD["STORAGE_KWARGS"]["location"].lstrip("/")}
GRADES_DOWNLOAD["STORAGE_KWARGS"]["bucket_name"] = "{{ S3_GRADE_BUCKET }}"
```

Note that I didn't use the plugin, but just used `GRADES_DOWNLOAD` config mentioned above and it didn't work. 
If this is a valid issue, I would like to work on it.

**Comment by DawoudSheraz** [comment]
@FahadKhalid210 FYI
