### ISSUE TITLE
PROFILE_IMAGE_BACKEND settings disappeared after v16.0.4

### ISSUE THREAD

**Issue by dyudyunov** [overhangio/tutor-minio#46]
The PROFILE_IMAGE_BACKEND settings were present from the [v14](https://github.com/overhangio/tutor-minio/blob/v14.0.0/tutorminio/patches/openedx-lms-common-settings) to v16.0.4 (latest before v17).

Here is the [PR where it was added](https://github.com/overhangio/tutor-minio/pull/10) and the [merge commit](https://github.com/overhangio/tutor-minio/commit/6a66a1a2f31dbab30daa8cabab8323b5fa05b028) from it.

But they are absent starting from v17 and now I can reproduce the issue from the mentioned PR (an uploaded profile picture disappears after the redeploy because it is stored locally).

I checked the repo several times but don't know what I'm missing here. What happened? Why did the setting disappear?

Notes: 
- without updated PROFILE_IMAGE_BACKEND settings profile images will be stored locally and lost after the next deployment on k8s installations.
- I tested it with redwood.2 release (tutor v18.1.3, minio v18.0.0)

**Comment by DawoudSheraz** [comment]
Hi. The setting was removed when upgrading to quince to fix an issue with profile photos. It seems some items might still be needed.

- https://github.com/overhangio/tutor-minio/pull/31
- https://github.com/openedx/wg-build-test-release/issues/333

**Comment by dyudyunov** [comment]
Just for history - here is my profile image backend config:
```
PROFILE_IMAGE_BACKEND = {
    "class": DEFAULT_FILE_STORAGE,
    "options": {
        # The bucket name value corresponds to default value of {{ MINIO_BUCKET_NAME }} - the only public bucket
        # https://github.com/overhangio/tutor-minio/blob/master/tutorminio/templates/minio/tasks/minio/init.sh#L6C31-L6C48 AFAIK
        "bucket_name": "openedx",  
        "querystring_auth": False,
        "location": PROFILE_IMAGE_BACKEND["options"]["location"].lstrip("/"),
    },
}
```
I was unable to use the private bucket because of the `SignatureDoesNotMatch` error. 

As I understood from the shallow investigation - querystring_auth doesn't work because `_get_profile_image_urls` appends additional querystring kwarg `&v=...`. If you remove it from the URL - signature works as expected.

**Comment by Faraz32123** [comment]
hello @dyudyunov, hope you are doing well.
Regarding the issue you have created, we have tested it on K8s locally, but we were unable to resolve the issue with below patch. Would you like to open a working PR?
```
# LMS-specific media storage
PROFILE_IMAGE_BACKEND = {
    "class": "storages.backends.s3boto3.S3Boto3Storage",
    "options": {
        "bucket_name": "{{ MINIO_BUCKET_NAME }}",
        "querystring_auth": False,
        "location": PROFILE_IMAGE_BACKEND["options"]["location"].lstrip("/"),
    },
}
```

The error we were facing:
```
 File "/openedx/venv/lib/python3.11/site-packages/botocore/httpsession.py", line 493, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://files.local.edly.io/openedx/openedx/media/profile-images/f70cff94eafe7e44b9bfcef3698d14bb_500.jpg"
```

**Comment by dyudyunov** [comment]
Hi @Faraz32123 

Sure, I would like to propose the fix, but I have a lack of time now and can't project the due date.

Interesting, I didn't see the error you mentioned. Can you use any other uploads except the profile image? Maybe there are some global-level misconfigurations...

**Comment by Faraz32123** [comment]
> Hi @Faraz32123
> 
> Sure, I would like to propose the fix, but I have a lack of time now and can't project the due date.
> 
> Interesting, I didn't see the error you mentioned. Can you use any other uploads except the profile image? Maybe there are some global-level misconfigurations...

Hello @dyudyunov, thanks for your reply!
We are currently investigating the issue 🔍 and will work on a fix soon.
