### ISSUE TITLE
Pulling minio

### ISSUE THREAD

**Issue by amarshalkin** [overhangio/tutor-minio#6]
After `tutor local quickstart ` i have a message:

```
Pulling minio (docker.io/minio/minio:RELEASE.2021-05-18T00-53-28Z)...
ERROR: manifest for minio/minio:RELEASE.2021-05-18T00-53-28Z not found: manifest unknown: manifest unknown
```
Then my actions are following:
1. for mc i use RELEASE.2021-06-08T01-29-37Z 
2. for minio i use RELEASE.2021-06-07T21-40-51Z  

And its work

**Comment by regisb** [comment]
Thanks for the heads up @amarshalkin! This was caused by the yanking of a few version from the docker.io registry. This should be fixed in the latest release.
