### ISSUE TITLE
Job error: `sh` is not a recognized command

### ISSUE THREAD

**Issue by imantaba** [overhangio/tutor-minio#9]
After enabling tutor-minio plugin in tutor k8s deployment it seems we faced an issue with it's job 

```
mc: <ERROR> `sh` is not a recognized command. Get help using `--help` flag.
Did you mean one of these?
`share`
```

Ref: https://discuss.overhang.io/t/minio-plugin-job-error/1772

**Comment by regisb** [comment]
This will be resolved by this PR: https://github.com/overhangio/tutor/pull/470
